<?php require_once 'nav.phtml'; ?>

<main>
	<div class="achats">
        <div class="equipes">
            <p class="fonda"> Fondateur </p>
        </div>
		<div class="sos">
			<div class="objets">
				<img src="image/strheilon.png"><br>
				<p class="fonda">DavidDc</p>
			</div>
            <div class="objets">
				<img src="image/strheilon.png"><br>
				<p class="fonda">Renaud</p>
			</div>
        </div>
        <div class="equipes">
            <p class="admin"> Administratrice </p>
        </div>
        <div class="sos">
            <div class="objets">
				<img src="image/strheilon.png"><br>
				<p class="admin">Haxana</p>
			</div>
            <div class="objets">
				<img src="image/strheilon.png"><br>
				<p class="admin">ChloeAs</p>
			</div>
        </div>
        <div class="equipes">
            <p class="modo"> Modérateur </p>
        </div>
        <div class="sos">
            <div class="objets">
				<img src="image/strheilon.png"><br>
				<p class="modo">Severn</p>
			</div>
        </div>
        <div class="equipes">
            <p class="media"> Médiateur </p>
        </div>
        <div class="sos">
            <div class="objets">
				<img src="image/strheilon.png"><br>
				<p class="media">Mr_Youngman</p>
			</div>
        </div>
    </div>
</main>
