<head>
	<link rel="stylesheet" href="././css/style.css">
	<link rel="stylesheet" href="././css/normalize.css">
	<link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	<title>Project Brawl</title>
	<meta charset="utf-8">
	<script src="././js/index.js"></script>
</head>
