<main>
    <?php require 'src/nav.phtml'; ?>
    <div class="buy">
        <h2>Ajouter un Match</h2>
        <form action="match.php" method="POST" enctype="multipart/form-data">
            <div class="form">
                <div class="match">
                    <label for="product">Nom de ce Match :</label>
                    <input name="match" type="product" class="writen" placeholder="Nom du Match">
                </div>
                <div class="match">
                    <label for="product">Liste des Participants :</label>
                    <input name="player" type="product" class="writen" placeholder="Ex : Pseudo,Pseudo,Pseudo,Pseudo">
                </div>
                <div class="match">
                    <label for="product">Victoire du Joueur : </label>
                    <input name="player_win" type="product" class="writen" placeholder="Nom du Vainqueur">
                </div>
            </div>
            <ul>
                <li>
                    <button class="button" type="submit">Ajouter</button>
                </li>
            </ul>
        </form>
    </div>
</main>
